### ISSUE TITLE
in Commit Changes dialog - "Show Diff" not working properly

### ISSUE THREAD

**Issue by chenop** [codebling/CommunityCase#11] opened 2014-05-26 06:18 UTC
Hi,

First of all great plug-in!
Got an issue with "Show Diff" action in the "Commit Changes" dialog.

Here is how to reproduce:
VCS --> Commit Changes --> Got the list of changes
Double click file1 --> Got the diffs of file1
Double click file2 --> Got the diffs of file1 (Expected the diffs of file2)

**Comment by codebling** [comment] 2014-05-26 20:14
Looking at it right now

**Comment by codebling** [comment] 2014-05-26 21:24
I'm not able to reproduce this unless the second file name has a space in it. Then cleartool is displeased and an error is shown before the diff of the last file is erroneously displayed. Is this what's happening to you?

**Comment by codebling** [comment] 2014-05-29 05:37
I think this is probably the problem you were experiencing. It should be fixed now. Please reopen if not. Fixed by issue #13

**Closed as completed by codebling** 2014-05-29 05:37 UTC
